### ISSUE TITLE
TextDisplayBase.hx:7: characters 12-39 : Type not found : TextStyle

### ISSUE THREAD

**Issue by alamboley** [haxeui/haxeui-pixijs#1]
Hey, just wanted to give finally a try to Haxe UI but I'm getting this error: `src/haxe/ui/backend/TextDisplayBase.hx:7: characters 12-39 : Type not found : TextStyle`.

It seems `TextStyle` isn't defined at all.

**Comment by hoseyjoe** [comment]
I think you can replace TextStyle with TextStyleObject
You will need to import
import pixi.core.text.TextStyleObject;

Also  in the updateFont(){ 
Change _style.font to _style.fontFamily

**Comment by ianharrigan** [comment]
What version of pixi is this? Do you have a test project? This would have been working at some point, so maybe there is a version mismatch?

**Comment by alamboley** [comment]
Hey, thanks for your help. I just made a Pull Request, I'm using the latest version of haxe pixijs.
