### ISSUE TITLE
AbsoluteLayout problem

### ISSUE THREAD

**Issue by Helgiii** [haxeui/haxeui-pixijs#9]
I can use vertical and horizontal layouts, but Absolute is not working for me at the moment.
I use git master branches for: haxeui-core, haxeui-pixijs, 
and pixijs 4.8.4

var cont:Box = new Box();
//cont.layout = new HorizontalLayout();
cont.layout = new AbsoluteLayout();

**Comment by ianharrigan** [comment]
Ill check it out... thanks!

**Comment by ianharrigan** [comment]
my initial tests seem to work:

![image](https://user-images.githubusercontent.com/3024242/73597320-efa91500-452a-11ea-96c4-d20385916975.png)

Im not using the same pixijs as you though, ill try that next... do you get an error or something? This is my testapp:

```haxe
            var box = new Box();
            box.layout = new VerticalLayout();
            var button = new Button();
            button.text = "Button 1";
            box.addComponent(button);
            var button = new Button();
            button.text = "Button 2";
            box.addComponent(button);
            var button = new Button();
            button.text = "Button 3";
            box.addComponent(button);
            main.addComponent(box);
            

            var box = new Box();
            box.layout = new AbsoluteLayout();
            var button = new Button();
            button.left = 10;
            button.top = 10;
            button.text = "Button 1";
            box.addComponent(button);
            var button = new Button();
            button.left = 20;
            button.top = 20;
            button.text = "Button 2";
            box.addComponent(button);
            var button = new Button();
            button.left = 30;
            button.top = 30;
            button.text = "Button 3";
            box.addComponent(button);
            main.addComponent(box);
```

PS: id kinda forgotten about the pixijs tbh, id love to know your use case for it - i though no one used it!

**Comment by Helgiii** [comment]
Wow, your example works great.
I see that I use x,y instead of left, top, but they used to work fine for me in haxeui-openfl

**Comment by ianharrigan** [comment]
Right, thats because the x/y are properties on pixi, not haxeui, i think in openfl i overrode the openfl setters to inform haxeui that the position had changed, ill see if thats something thats possible in pixi too

**Comment by Helgiii** [comment]
cool, thanx for clarifying this
